name: realtime-project

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.8.7
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    container_name: roblox_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: roblox_db
    ports:
      - "5433:5432" # AMAN: Tidak bentrok dengan steam_db
    volumes:
      - roblox_pgdata:/var/lib/postgresql/data # Ganti nama volume agar unik
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  roblox_pgdata: # Nama volume yang lebih spesifik
